import { FormaComporta, PosicaoDobradica } from './tipos';
import { ConfiguracaoSimulacaoComporta } from './configuracao';

export const PRESETS: { [key: string]: ConfiguracaoSimulacaoComporta & { title: string, subtitle: string } } = {
  comportaVertical: {
    title: "Comporta Vertical",
    subtitle: "Clássica θ = 90°",
    fluidoMontante: { chave: 'agua', nivel: 12, densidade: 1000, gravidade: 9.81 },
    fluidoJusante: { chave: 'agua', nivel: 0, densidade: 1000, gravidade: 9.81, ativo: false },
    comporta: {
      ativa: true,
      forma: FormaComporta.RETANGULAR,
      largura: 2,
      altura: 3,
      profundidadeTopo: 4,
      angulo: 90,
      posicaoDobradica: PosicaoDobradica.TOP,
      temTirante: true,
      posicaoTiranteRelativa: 1,
      anguloTirante: 0,
      pesoProprio: 500,
      pesoProprioAtivo: false,
    }
  },
  doisFluidos: {
    title: "Dois Fluidos",
    subtitle: "Glicerina × Água a 30°",
    fluidoMontante: { chave: 'glicerina', nivel: 5, densidade: 1260, gravidade: 9.81 },
    fluidoJusante: { chave: 'agua', nivel: 4, densidade: 1000, gravidade: 9.81, ativo: true },
    comporta: {
      ativa: true,
      forma: FormaComporta.RETANGULAR,
      largura: 3,
      altura: 4,
      profundidadeTopo: 2,
      angulo: 30,
      posicaoDobradica: PosicaoDobradica.BOTTOM,
      temTirante: false,
      posicaoTiranteRelativa: 1,
      anguloTirante: 0,
      pesoProprio: 0,
      pesoProprioAtivo: false,
    }
  },
  comportaInclinada45: {
    title: "Inclinada 45°",
    subtitle: "Articulada em B",
    fluidoMontante: { chave: 'agua', nivel: 4, densidade: 1000, gravidade: 9.81 },
    fluidoJusante: { chave: 'agua', nivel: 0, densidade: 1000, gravidade: 9.81, ativo: false },
    comporta: {
      ativa: true,
      forma: FormaComporta.RETANGULAR,
      largura: 5,
      altura: 4.243,
      profundidadeTopo: 0.5,
      angulo: 45,
      posicaoDobradica: PosicaoDobradica.BOTTOM,
      temTirante: false,
      posicaoTiranteRelativa: 0,
      anguloTirante: 0,
      pesoProprio: 0,
      pesoProprioAtivo: false,
    }
  },
  semicircularFundo: {
    title: "Semicircular",
    subtitle: "Vista lateral R = 3m",
    fluidoMontante: { chave: 'agua', nivel: 8, densidade: 1000, gravidade: 9.81 },
    fluidoJusante: { chave: 'agua', nivel: 0, densidade: 1000, gravidade: 9.81, ativo: false },
    comporta: {
      ativa: true,
      forma: FormaComporta.SEMI_CIRCULAR,
      largura: 6,
      altura: 3,
      profundidadeTopo: 5,
      angulo: 90,
      posicaoDobradica: PosicaoDobradica.NONE,
      temTirante: false,
      posicaoTiranteRelativa: 1,
      anguloTirante: 0,
      pesoProprio: 0,
      pesoProprioAtivo: false,
    }
  },
  comportaCircular: {
    title: "Comporta Circular",
    subtitle: "Fundo de Reservatório",
    fluidoMontante: { chave: 'agua', nivel: 18, densidade: 1000, gravidade: 9.81 },
    fluidoJusante: { chave: 'agua', nivel: 0, densidade: 1000, gravidade: 9.81, ativo: false },
    comporta: {
      ativa: true,
      forma: FormaComporta.CIRCULAR,
      largura: 2,
      altura: 2,
      profundidadeTopo: 15,
      angulo: 45,
      posicaoDobradica: PosicaoDobradica.NONE,
      temTirante: false,
      posicaoTiranteRelativa: 1,
      anguloTirante: 0,
      pesoProprio: 0,
      pesoProprioAtivo: false,
    }
  },
  comportaDupla: {
    title: "Dois Lados",
    subtitle: "Água × Água com jusante",
    fluidoMontante: { chave: 'agua', nivel: 22, densidade: 1000, gravidade: 9.81 },
    fluidoJusante: { chave: 'agua', nivel: 5, densidade: 1000, gravidade: 9.81, ativo: true },
    comporta: {
      ativa: true,
      forma: FormaComporta.RETANGULAR,
      largura: 4,
      altura: 5,
      profundidadeTopo: 10,
      angulo: 60,
      posicaoDobradica: PosicaoDobradica.BOTTOM,
      temTirante: true,
      posicaoTiranteRelativa: 0,
      anguloTirante: 30,
      pesoProprio: 2000,
      pesoProprioAtivo: true,
    }
  },
  oleoAgua: {
    title: "Óleo × Água",
    subtitle: "Fluidos imiscíveis",
    fluidoMontante: { chave: 'oleoSAE30', nivel: 6, densidade: 891, gravidade: 9.81 },
    fluidoJusante: { chave: 'agua', nivel: 5, densidade: 1000, gravidade: 9.81, ativo: true },
    comporta: {
      ativa: true,
      forma: FormaComporta.RETANGULAR,
      largura: 3,
      altura: 3,
      profundidadeTopo: 2,
      angulo: 90,
      posicaoDobradica: PosicaoDobradica.NONE,
      temTirante: false,
      posicaoTiranteRelativa: 1,
      anguloTirante: 0,
      pesoProprio: 0,
      pesoProprioAtivo: false,
    }
  },
};
